### ISSUE TITLE
Is it possible to run it without a real backend?

### ISSUE THREAD

**Issue by tylerlong** [Coding/WebIDE-Frontend#1]
I am wondering if I can run it as a pure frontend library, just like the ACE editor.

Is it possible to create a "mock backend" and run the frontend without https://github.com/Coding/WebIDE-Backend ?

**Comment by hackape** [comment]
In theory yes. If you provided a backend, mock or real, that conforms to the same API, you can get the frontend running. But this project is still at an very early stage, we don't have all the APIs documented yet, so I recommend you just stick with the backend we provide for now.

**Comment by hackape** [comment]
Actually everything is well configured, you shouldn't encounter much difficulty to run a backend. Please do refer to the [WebIDE-Workspace/](https://github.com/Coding/WebIDE-Workspace/), there we include shell scripts to kickstart the thing.
