### ISSUE TITLE
新建一个文件没找到保存方法

### ISSUE THREAD

**Issue by Honghe** [Coding/WebIDE-Frontend#2]
新建一个文件没找到保存方法。
同时，跟 coding.net 上的 IDE 比，很多功能/按钮都没有，是未准备好放出来，还是特意删减的？

**Comment by hackape** [comment]
是的…这个项目的前端是重写的，还缺很多功能，现在顶多算 alpha，还请耐心等待一段时间。

**Comment by hackape** [comment]
暂时你可以到 `app/commands/keymap.js` 设置一个快捷键给 'file:save' 命令来解决这个问题。

保存后目前还没做文件状态提示，但是关闭再打开标签页可以看到保存是生效的。

**Comment by Honghe** [comment]
用 React 重写很赞，目前也在折腾 React
