### ISSUE TITLE
感觉依赖没说清楚啊

### ISSUE THREAD

**Issue by owtotwo** [Coding/WebIDE-Frontend#4]
Node什么的……还有es6-promise（不知道是不是版本问题）
然后sh.js的那个repository不能fetch下来导致后面环境出问题

**Comment by hackape** [comment]
确实，下周会解决这个问题。

**Comment by owtotwo** [comment]
感谢回复……很喜欢你们的产品

**Comment by hackape** [comment]
86693eb973b030c44bb5a70763d9cc6ae6fe7ac0 加了版本要求，并修了些遗漏的依赖声明。
